import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Generated from the folders of docs/ (the manual) and api/ (the API reference).
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
