using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Unity.Mathematics;
using Unity.Profiling;
using UnityEngine;
using UnityEngine.TextCore.Text;

namespace Yaui.Text
{
    internal struct TextRequest
    {
        public FontAsset Font;

        /// <summary>Points; one point is one canvas unit.</summary>
        public float FontSize;

        public Color32 Color;
        public TextAlign Align;
        public bool WordWrap;
        public bool RichText;

        /// <summary>Ends the text with an ellipsis where it overflows the size given to <see cref="AtgText.Generate(float, float)"/>.</summary>
        public bool Ellipsis;

        /// <summary>The sprites of &lt;sprite&gt; tags, or null.</summary>
        public SpriteAsset SpriteAsset;
    }

    /// <summary>A glyph quad relative to the top-left of the text, in canvas units with Y down.</summary>
    internal struct GlyphQuad
    {
        public float2 Min;
        public float2 Max;

        /// <summary>Horizontal offset of the top edge per unit of height (italic).</summary>
        public float Skew;

        /// <summary>xy: UV at <see cref="Min"/>, zw: UV at <see cref="Max"/>.</summary>
        public float4 Uv;

        public Color32 Color;
        public Texture Atlas;

        /// <summary>A sprite of a sprite asset (a color texture) rather than an SDF glyph.</summary>
        public bool IsSprite;

        /// <summary>Distance field spread in texels.</summary>
        public float Spread;

        public bool Bold;
    }

    /// <summary>
    /// Text generated by the Advanced Text Generator, in stages so that the expensive native part can run on
    /// worker threads (planning/poc3-text.md): <see cref="Prepare"/> (main thread), <see cref="Generate"/> (any
    /// thread, may be repeated with other widths), <see cref="ResolveMissingGlyphs"/> (main thread, once for a
    /// batch) and <see cref="Convert"/> (main thread).
    /// </summary>
    internal sealed unsafe class AtgText : IDisposable
    {
        // Canvas units around each glyph quad: enough for anti-aliasing and synthesized bold, without filling
        // much empty atlas area.
        internal const int VertexPadding = 2;

        static readonly ProfilerMarker GenerateMarker = new("Yaui.Text.Generate");
        static readonly ProfilerMarker ResolveMissingMarker = new("Yaui.Text.ResolveMissingGlyphs");
        static readonly ProfilerMarker ConvertMarker = new("Yaui.Text.Convert");

        static TextSettings textSettings;

        // Text settings whose default sprite asset is the sprite asset of a text: ATG resolves <sprite> through them.
        static readonly Dictionary<SpriteAsset, TextSettings> SpriteSettings = new();
        static object textInfoList;
        static readonly List<uint> GlyphBuffer = new();
        static readonly Dictionary<EntityId, HashSet<uint>> AggregatedMissingGlyphs = new();

        IntPtr textGenerationInfo;
        NativeTextGenerationSettings settings;
        NativeTextInfo textInfo;
        bool hasMissingGlyphs;

        // ProcessMeshInfos maps the UVs in place, so it must run once per native generation: a cached generation
        // (the same text prepared again, e.g. by OnValidate after an undo) already has atlas UVs.
        bool uvsAreGenerated;
        bool wordWrap;
        bool ellipsis;

        // Pinned so that worker threads can pass it to the native generator.
        char[] textBuffer;
        GCHandle textBufferHandle;

        List<List<List<int>>> textElementIndicesByMesh = new();
        Dictionary<EntityId, HashSet<uint>> missingGlyphs = new();

        /// <summary>Uses the public TextGenerator even if the internal APIs match (tests).</summary>
        internal static bool ForceFallback;

        /// <summary>Whether the internal ATG APIs match this Unity version; otherwise texts use <see cref="FallbackText"/>.</summary>
        public static bool IsSupported => !ForceFallback && AtgInternals.Initialize();

        public AtgText()
        {
            textGenerationInfo = AtgInternals.CreateGenerationInfo(true);
            EnsureTextBuffer(32);
        }

        /// <summary>The native generation info: <see cref="AtgSelection"/> queries its last generation.</summary>
        public IntPtr GenerationInfo => textGenerationInfo;

        public bool IsPrepared { get; private set; }

        /// <summary>Whether <see cref="Generate"/> ran since <see cref="Prepare"/>.</summary>
        public bool IsGenerated { get; private set; }

        /// <summary>The width of the last generation, or a negative value if unconstrained.</summary>
        public float GeneratedWidth { get; private set; } = -1f;

        /// <summary>
        /// The height the last generation was elided to, or a negative value if it was not: its size is then not the
        /// size of the text.
        /// </summary>
        public float ElidedHeight { get; private set; } = -1f;

        /// <summary>Size of the last generation.</summary>
        public float2 Size { get; private set; }

        static TextSettings TextSettings
        {
            get
            {
                if (textSettings == null)
                {
                    textSettings = ScriptableObject.CreateInstance<TextSettings>();
                    textSettings.hideFlags = HideFlags.HideAndDontSave;
                }

                return textSettings;
            }
        }

        static TextSettings SettingsFor(SpriteAsset spriteAsset)
        {
            if (spriteAsset == null)
            {
                return TextSettings;
            }

            if (!SpriteSettings.TryGetValue(spriteAsset, out var settings) || settings == null)
            {
                settings = ScriptableObject.CreateInstance<TextSettings>();
                settings.hideFlags = HideFlags.HideAndDontSave;
                settings.defaultSpriteAsset = spriteAsset;
                SpriteSettings[spriteAsset] = settings;
            }

            return settings;
        }

        /// <summary>Main thread: the dynamic SDF font asset of a font, shared like UI Toolkit does.</summary>
        public static FontAsset GetFontAsset(Font font) =>
            IsSupported ? AtgInternals.GetCachedFontAsset(TextSettings, font, false) : null;

        /// <summary>Main thread: must be called before <see cref="Generate"/> runs on worker threads.</summary>
        public static void PrepareForJobs() => AtgInternals.CreateHbFaceIfNeeded();

        /// <summary>Main thread: copies the text and builds the native settings, unconstrained in width.</summary>
        public void Prepare(ReadOnlySpan<char> text, in TextRequest request)
        {
            EnsureTextBuffer(text.Length);
            text.CopyTo(textBuffer);

            settings = BuildNativeSettings(request);
            settings.textBufferPtr = textBufferHandle.AddrOfPinnedObject();
            settings.textBufferLength = text.Length;
            wordWrap = request.WordWrap;
            ellipsis = request.Ellipsis;
            if (settings.richTextEnabled && text.Length > 0)
            {
                AtgInternals.PreloadAssetsFromText(settings.textBufferPtr, text.Length, settings.textSettings);
            }

            IsPrepared = true;
            IsGenerated = false;
        }

        /// <summary>Any thread: shapes and lays out the text within <paramref name="width"/> (negative: unconstrained).</summary>
        public void Generate(float width) => Generate(width, -1f);

        /// <summary>
        /// Any thread: like <see cref="Generate(float)"/>, and with <see cref="TextRequest.Ellipsis"/>, ends the text
        /// with an ellipsis where it overflows <paramref name="width"/> and <paramref name="height"/> (not negative).
        /// </summary>
        public void Generate(float width, float height)
        {
            using var _ = GenerateMarker.Auto();
            var constrained = width >= 0f;
            var elide = ellipsis && constrained && height >= 0f;
            settings.screenWidth = constrained ? ToFixedPoint(width) : -1;
            settings.screenHeight = elide ? ToFixedPoint(height) : -1;
            settings.overflow = elide ? AtgInternals.OverflowEllipsis : AtgInternals.OverflowClip;
            settings.wordWrapEnabled = wordWrap && constrained;
            ElidedHeight = elide ? height : -1f;

            var wasCached = false;
            textInfo = AtgInternals.GenerateText(AtgInternals.TextLib, settings, textGenerationInfo, ref wasCached);
            if (!wasCached)
            {
                uvsAreGenerated = false;
            }

            Size = new float2(textInfo.totalWidth / 64f, textInfo.totalHeight / 64f);
            GeneratedWidth = constrained ? width : -1f;
            IsGenerated = true;

            foreach (var set in missingGlyphs.Values)
            {
                set.Clear();
            }

            hasMissingGlyphs = AtgInternals.HasMissingGlyphs(AtgInternals.TextLib, textInfo, ref missingGlyphs);
            if (!hasMissingGlyphs)
            {
                ProcessMeshInfos();
            }
        }

        /// <summary>
        /// Main thread: adds the glyphs missing from any of the texts to the atlases (with OS font fallback) once,
        /// then resolves the UVs of those texts. Adding the same glyph twice throws, so they are aggregated.
        /// </summary>
        public static void ResolveMissingGlyphs(List<AtgText> texts)
        {
            if (texts.Count == 0)
            {
                return;
            }

            using var _ = ResolveMissingMarker.Auto();

            foreach (var set in AggregatedMissingGlyphs.Values)
            {
                set.Clear();
            }

            textInfoList ??= AtgInternals.CreateTextInfoList();
            AtgInternals.TextInfoListClear(textInfoList);
            var anyMissing = false;
            foreach (var text in texts)
            {
                if (!text.hasMissingGlyphs)
                {
                    continue;
                }

                anyMissing = true;
                AtgInternals.TextInfoListAdd(textInfoList, text.textInfo);
                foreach (var pair in text.missingGlyphs)
                {
                    if (pair.Value.Count == 0)
                    {
                        continue;
                    }

                    if (!AggregatedMissingGlyphs.TryGetValue(pair.Key, out var set))
                    {
                        AggregatedMissingGlyphs[pair.Key] = set = new HashSet<uint>();
                    }

                    set.UnionWith(pair.Value);
                }
            }

            if (!anyMissing)
            {
                return;
            }

            AtgInternals.ResolveFallbacks(textInfoList, AggregatedMissingGlyphs);
            foreach (var entry in AggregatedMissingGlyphs)
            {
                if (Resources.EntityIdToObject(entry.Key) is not FontAsset fontAsset || entry.Value.Count == 0)
                {
                    continue;
                }

                GlyphBuffer.Clear();
                GlyphBuffer.AddRange(entry.Value);
                AtgInternals.TryAddGlyphs(fontAsset, GlyphBuffer, false);
            }

            AtgInternals.CreateHbFaceIfNeeded();
            AtgInternals.UpdateFontAssetsInUpdateQueue();

            foreach (var text in texts)
            {
                if (text.hasMissingGlyphs)
                {
                    text.ProcessMeshInfos();
                    text.hasMissingGlyphs = false;
                }
            }
        }

        void ProcessMeshInfos()
        {
            foreach (var atlases in textElementIndicesByMesh)
            {
                foreach (var indices in atlases)
                {
                    indices.Clear();
                }
            }

            // Rasterizes newly added glyphs and fills the UVs.
            AtgInternals.ProcessMeshInfos(AtgInternals.TextLib, textInfo, settings, ref textElementIndicesByMesh,
                uvsAreGenerated);
            uvsAreGenerated = true;
        }

        /// <summary>Main thread: converts the last generation into glyph quads.</summary>
        public void Convert(List<GlyphQuad> output)
        {
            using var _ = ConvertMarker.Auto();
            output.Clear();

            var meshInfos = (ATGMeshInfo*)textInfo.m_MeshInfosPtr;
            var processedMeshIndex = 0;
            for (var i = 0; i < textInfo.meshInfoCount; i++)
            {
                var meshInfo = meshInfos[i];
                var textAsset = Resources.EntityIdToObject(meshInfo.textAssetId);
                if (textAsset is SpriteAsset spriteAsset)
                {
                    ConvertSprites(meshInfo, spriteAsset, output);
                    processedMeshIndex++;
                    continue;
                }

                if (textAsset is not FontAsset fontAsset)
                {
                    if (textAsset != null)
                    {
                        processedMeshIndex++;
                    }

                    continue;
                }

                var elements = (NativeTextElementInfo*)meshInfo.m_TextElementInfosPtr;
                var spread = fontAsset.IsBitmap() ? 0f : fontAsset.atlasPadding + 1f;
                var atlasIndices = textElementIndicesByMesh[processedMeshIndex];
                for (var atlasIndex = 0; atlasIndex < atlasIndices.Count; atlasIndex++)
                {
                    var atlas = fontAsset.atlasTextures[atlasIndex];
                    foreach (var elementIndex in atlasIndices[atlasIndex])
                    {
                        ref var e = ref elements[elementIndex];
                        var glyph = AtgInternals.GetGlyphInCache(fontAsset, (uint)e.glyphID);
                        if (glyph != null && (glyph.metrics.width <= 0f || glyph.metrics.height <= 0f))
                        {
                            continue;
                        }

                        // ATG lays out with Y up from the top-left (flipYAxis), so Y is negated.
                        var top = -e.topLeft.position.y;
                        var bottom = -e.bottomLeft.position.y;
                        var left = e.bottomLeft.position.x;
                        var right = e.bottomRight.position.x;
                        output.Add(new GlyphQuad
                        {
                            Min = new float2(left, top),
                            Max = new float2(right, bottom),
                            Skew = bottom > top ? (e.topLeft.position.x - left) / (bottom - top) : 0f,
                            Uv = new float4(e.bottomLeft.uv0.x, e.topRight.uv0.y, e.topRight.uv0.x,
                                e.bottomLeft.uv0.y),
                            Color = e.bottomLeft.color,
                            Atlas = atlas,
                            Spread = spread,
                            Bold = e.bottomLeft.uv2.y != 0,
                        });
                    }
                }

                processedMeshIndex++;
            }
        }

        /// <summary>The sprites of &lt;sprite&gt; tags: colored quads of the sprite sheet.</summary>
        static void ConvertSprites(ATGMeshInfo meshInfo, SpriteAsset spriteAsset, List<GlyphQuad> output)
        {
            var sheet = spriteAsset.spriteSheet;
            if (sheet == null)
            {
                return;
            }

            var elements = (NativeTextElementInfo*)meshInfo.m_TextElementInfosPtr;
            for (var i = 0; i < meshInfo.m_TextElementCount; i++)
            {
                ref var e = ref elements[i];
                var top = -e.topLeft.position.y;
                var bottom = -e.bottomLeft.position.y;
                var left = e.bottomLeft.position.x;
                var right = e.bottomRight.position.x;
                if (right <= left || bottom <= top)
                {
                    continue;
                }

                output.Add(new GlyphQuad
                {
                    Min = new float2(left, top),
                    Max = new float2(right, bottom),
                    Skew = (e.topLeft.position.x - left) / (bottom - top),
                    Uv = new float4(e.bottomLeft.uv0.x, e.topRight.uv0.y, e.topRight.uv0.x, e.bottomLeft.uv0.y),
                    Color = e.bottomLeft.color,
                    Atlas = sheet,
                    IsSprite = true,
                });
            }
        }

        void EnsureTextBuffer(int length)
        {
            if (textBuffer != null && textBuffer.Length >= length)
            {
                return;
            }

            if (textBufferHandle.IsAllocated)
            {
                textBufferHandle.Free();
            }

            textBuffer = new char[Math.Max(length, (textBuffer?.Length ?? 16) * 2)];
            textBufferHandle = GCHandle.Alloc(textBuffer, GCHandleType.Pinned);
        }

        static NativeTextGenerationSettings BuildNativeSettings(in TextRequest request)
        {
            var s = AtgInternals.GetDefaultSettings();
            s.fontAsset = AtgInternals.GetNativeFontAsset(request.Font);
            s.textSettings = AtgInternals.GetNativeTextSettings(SettingsFor(request.SpriteAsset));
            s.fontSize = ToFixedPoint(request.FontSize);
            s.color = request.Color;
            s.fontStyle = AtgInternals.FontStyleNormal;
            s.fontWeight = AtgInternals.FontWeightRegular;
            s.horizontalAlignment = request.Align switch
            {
                TextAlign.Center => AtgInternals.HorizontalCenter,
                TextAlign.Right => AtgInternals.HorizontalRight,
                TextAlign.Justified => AtgInternals.HorizontalJustified,
                _ => AtgInternals.HorizontalLeft,
            };

            // Vertical alignment is applied by YAUI, since the height is only known after the layout.
            s.verticalAlignment = AtgInternals.VerticalTop;
            s.flipYAxis = true;
            s.screenHeight = -1;
            s.overflow = AtgInternals.OverflowClip;
            s.languageDirection = AtgInternals.LanguageLtr;
            s.richTextEnabled = request.RichText;
            s.vertexPadding = ToFixedPoint(VertexPadding);
            s.pixelsPerPointFixed64 = 64;
            return s;
        }

        static int ToFixedPoint(float value) => (int)(value * 64f);

        public void Dispose()
        {
            if (textGenerationInfo != IntPtr.Zero)
            {
                AtgInternals.DestroyGenerationInfo(textGenerationInfo);
                textGenerationInfo = IntPtr.Zero;
            }

            if (textBufferHandle.IsAllocated)
            {
                textBufferHandle.Free();
            }
        }
    }
}
